config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'atrakcje' => 'static_pages#atrakcje'

  get 'cennik' => 'static_pages#cennik'

  get 'kontakt' => 'static_pages#kontakt'

  get 'galeria' => 'static_pages#galeria'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "Hello World! Here I come!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def atrakcje
  end

  def cennik
  end

  def kontakt
  end

  def galeria
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = "")
        base_title = "Agroturystyka Radolinek 39"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end    
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Radolinek webpage by M&M's
    </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Strona główna", root_path %></li>
                <li><%= link_to "Atrakcje", atrakcje_path %></li>
                <li><%= link_to "Cennik", cennik_path %></li>
                <li><%= link_to "Kontakt", kontakt_path %></li>
                <li><%= link_to "Galeria", galeria_path %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    'application', media: 'all',  'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%=render 'layouts/shim'%>
    </head>
    <body>
        <%= render 'layouts/header'%>
        <div class="container">
            <%= yield %>
            <%= render 'layouts/footer'%>
    </body>
</html>

app/views/static_pages/atrakcje.html.erb
<%provide(:title, "Atrakcje")%>

    <h1>Atrakcje w okolicy Radolinka</h1>
        <p>
            Las
            Grzyby
            Rzeka
            Spokój
        </p>
    

app/views/static_pages/cennik.html.erb
<%provide(:title, "Cennik")%>

    <h1>Cennik</h1>
        <p>
        Ceny noclegów
        </p>
    

app/views/static_pages/galeria.html.erb
<%provide(:title, "Galeria")%>
   
        <h1>Galeria</h1>
        <p>
        Zdjęcia okolicy i nie tylko...
        </p>
    

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Radolinek 39</h1>
    <h2>
        Witajcie w agroturystyce Radolinek 39! 
    </h2>
    
    <%= link_to "Rezerwacja", '#', class: "btn btn-lg btn-primary"%>
</div>    
<%= image_tag("test.jpg", class: "centered-img", alt: "test")%>

app/views/static_pages/kontakt.html.erb
<%provide(:title, "Kontakt")%>

        <h1>Kontakt</h1>
        <p>
        Skontaktuj się z nami:
        telefon:
        mail:
        adres:
        </p>
   